-- Add faults and block columns to players table
ALTER TABLE players
ADD COLUMN IF NOT EXISTS faltas INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS bloqueado_ate TIMESTAMP WITH TIME ZONE;

-- Add timing and payment tracking to bets table
ALTER TABLE bets
ADD COLUMN IF NOT EXISTS aceita_em TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS partida_iniciada_em TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS p1_pagou BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS p2_pagou BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS revisao_manual BOOLEAN DEFAULT FALSE;
